TrainingArguments:
  num_train_epochs: 3
  warmup_steps: 1000
  per_device_train_batch_size: 2
  weight_decay: 0.01
  logging_steps: 50
  evaluation_strategy: epoch
  eval_steps: 0
  save_steps: 1000
  gradient_accumulation_steps: 8